
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetInfoMov", targetNamespace = "http://ws/", wsdlLocation = "http://192.168.40.112:9090/WebServiceMov/GetInfoMov?WSDL")
public class GetInfoMov_Service
    extends Service
{

    private final static URL GETINFOMOV_WSDL_LOCATION;
    private final static WebServiceException GETINFOMOV_EXCEPTION;
    private final static QName GETINFOMOV_QNAME = new QName("http://ws/", "GetInfoMov");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.40.112:9090/WebServiceMov/GetInfoMov?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETINFOMOV_WSDL_LOCATION = url;
        GETINFOMOV_EXCEPTION = e;
    }

    public GetInfoMov_Service() {
        super(__getWsdlLocation(), GETINFOMOV_QNAME);
    }

    public GetInfoMov_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETINFOMOV_QNAME, features);
    }

    public GetInfoMov_Service(URL wsdlLocation) {
        super(wsdlLocation, GETINFOMOV_QNAME);
    }

    public GetInfoMov_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETINFOMOV_QNAME, features);
    }

    public GetInfoMov_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetInfoMov_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetInfoMov
     */
    @WebEndpoint(name = "GetInfoMovPort")
    public GetInfoMov getGetInfoMovPort() {
        return super.getPort(new QName("http://ws/", "GetInfoMovPort"), GetInfoMov.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetInfoMov
     */
    @WebEndpoint(name = "GetInfoMovPort")
    public GetInfoMov getGetInfoMovPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "GetInfoMovPort"), GetInfoMov.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETINFOMOV_EXCEPTION!= null) {
            throw GETINFOMOV_EXCEPTION;
        }
        return GETINFOMOV_WSDL_LOCATION;
    }

}
